version: '3'
services:
  mqtt-broker:
    image: eclipse-mosquitto
    container_name: mqtt-broker
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - mosquitto-config:/mosquitto/config
      - mosquitto-data:/mosquitto/data
      - mosquitto-log:/mosquitto/log

  mqtt-publisher:
    build:
      context: ./mqtt-publisher  # Replace with the path to your MQTT publisher code
    depends_on:
      - mqtt-broker
    environment:
      - MQTT_BROKER_HOST=mqtt-broker
    networks:
      - my-network

  mqtt-subscriber:
    build:
      context: ./mqtt-subscriber  # Replace with the path to your MQTT subscriber code
    depends_on:
      - mqtt-broker
      - mongodb
    environment:
      - MQTT_BROKER_HOST=mqtt-broker
      - MONGO_HOST=mongodb
    networks:
      - my-network

  mongodb:
    image: mongo
    container_name: mymongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=yusharth
      - MONGO_INITDB_ROOT_PASSWORD=fcukdwrld
    volumes:
      - mongodb-data:/data/db

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

networks:
  my-network:
    driver: bridge

volumes:
  mosquitto-config:
  mosquitto-data:
  mosquitto-log:
  mongodb-data:
